from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from utils.logging_utils import PipelineLogger
from utils.path_utils import load_yaml, resolve_project_paths
from utils.table_utils import read_table, write_table


SCRIPT_README = """# Run the OriginPro batch script

This folder contains an OriginPro-side helper script generated by the Python pipeline.
It is intended to be run inside OriginPro, not by Python.

## Files

- `build_origin_project.ogs`: LabTalk/OGS script for importing the Origin-ready CSV files and creating editable graph pages.
- `../origin_input/origin_plot_manifest.xlsx`: human-readable graph manifest.
- `../origin_input/origin_plot_manifest.csv`: CSV copy used by the script.

## How to run

1. Open OriginPro.
2. Open the Script Window.
3. Run `run.section("path\\to\\build_origin_project.ogs", Main)`.
4. Inspect the generated graph pages.
5. Apply or refine graph templates manually if your Origin version does not apply them automatically.
6. Save or reopen the generated OPJU under `../opju_outputs/`.

The script imports worksheet data and plots from columns. It does not insert matplotlib PNGs as graph content.
"""


def _origin_cfg(config: dict) -> dict:
    return config.get("origin", {})


def _sanitize_origin_name(value: object, *, default: str = "origin_page", max_len: int = 48) -> str:
    safe = re.sub(r"[^0-9A-Za-z_]+", "_", str(value or "").strip())
    safe = re.sub(r"_+", "_", safe).strip("_")
    if not safe:
        safe = default
    if safe[0].isdigit():
        safe = f"g_{safe}"
    return safe[:max_len]


def _sanitize_windows_filename(value: str, *, default: str = "neuroexplorer_fullrate_aligned_project") -> str:
    sanitized = re.sub(r'[<>:"/\\|?*\x00-\x1f]+', "_", str(value or "").strip())
    sanitized = re.sub(r"\s+", "_", sanitized)
    sanitized = re.sub(r"_+", "_", sanitized).strip(" ._")
    return sanitized or default


def _project_name(config: dict, paths: dict) -> str:
    raw_name = config.get("project", {}).get("name") or paths["root_dir"].name or "neuroexplorer_fullrate_aligned_project"
    return _sanitize_windows_filename(str(raw_name))


def _opju_output_path(config: dict, paths: dict) -> Path:
    origin_cfg = _origin_cfg(config)
    project_name = _project_name(config, paths)
    filename_template = origin_cfg.get("opju_filename", "{project_name}_fullrate_aligned.opju")
    filename = _sanitize_windows_filename(filename_template.format(project_name=project_name))
    if not filename.lower().endswith(".opju"):
        filename = f"{filename}.opju"
    return paths["origin_output_dir"] / filename


def _lt_path(path: Path) -> str:
    return Path(path).resolve().as_posix()


def _read_manifest(manifest_xlsx: Path, manifest_csv: Path) -> pd.DataFrame:
    if manifest_xlsx.exists():
        manifest_df = read_table(manifest_xlsx)
        write_table(manifest_df, manifest_csv)
        return manifest_df
    if manifest_csv.exists():
        return read_table(manifest_csv)
    empty = pd.DataFrame(
        columns=[
            "file_id",
            "unit_id",
            "figure_type",
            "input_csv",
            "x_column",
            "y_column",
            "output_graph_name",
            "output_png_path",
            "notes",
        ]
    )
    write_table(empty, manifest_csv)
    return empty


def _load_origin_table(paths: dict, filename: str) -> pd.DataFrame:
    table_path = paths["origin_input_dir"] / filename
    if not table_path.exists():
        return pd.DataFrame()
    return read_table(table_path)


def _unit_original_name_map(paths: dict) -> dict[tuple[str, str], str]:
    unit_table = _load_origin_table(paths, "unit_quality_table_for_origin.csv")
    if unit_table.empty or "original_name" not in unit_table.columns:
        return {}
    mapping: dict[tuple[str, str], str] = {}
    for _, row in unit_table.iterrows():
        file_id = str(row.get("file_id", "")).strip()
        unit_id = str(row.get("unit_id", "")).strip()
        original_name = str(row.get("original_name", "")).strip()
        if file_id and unit_id and original_name:
            mapping[(file_id, unit_id)] = original_name
    return mapping


def _filter_unit_rows(df: pd.DataFrame, row: pd.Series, unit_name_map: dict[tuple[str, str], str]) -> pd.DataFrame:
    if df.empty:
        return df
    filtered = df.copy()
    file_id = str(row.get("file_id", "")).strip()
    unit_id = str(row.get("unit_id", "")).strip()
    if file_id and "file_id" in filtered.columns:
        filtered = filtered[filtered["file_id"].astype(str) == file_id]
    candidate_unit_ids = [unit_id]
    original_name = unit_name_map.get((file_id, unit_id))
    if original_name:
        candidate_unit_ids.append(original_name)
    if unit_id and "unit_id" in filtered.columns:
        filtered = filtered[filtered["unit_id"].astype(str).isin(candidate_unit_ids)]
    if "trial_id" in filtered.columns:
        aggregated = filtered[filtered["trial_id"].astype(str).str.lower() == "aggregated"]
        if not aggregated.empty:
            filtered = aggregated
    return filtered


def _write_graph_input_csv(row: pd.Series, paths: dict, table_cache: dict[str, pd.DataFrame], unit_name_map: dict[tuple[str, str], str]) -> Path | None:
    input_csv = str(row.get("input_csv", "")).strip()
    if not input_csv:
        return None
    source_df = table_cache.setdefault(input_csv, _load_origin_table(paths, input_csv))
    if source_df.empty:
        return None
    figure_type = str(row.get("figure_type", "")).lower()
    graph_name = _sanitize_origin_name(row.get("output_graph_name", ""), default="origin_graph")
    filtered = _filter_unit_rows(source_df, row, unit_name_map)
    if filtered.empty:
        return None
    if "prelightpost" in figure_type or "prepost" in figure_type:
        value_columns = ["baseline_hz", "light_hz", "post_hz"]
        if not all(column in filtered.columns for column in value_columns):
            return None
        first = filtered.iloc[0]
        graph_df = pd.DataFrame(
            {
                "condition_index": [1, 2, 3],
                "firing_rate_hz": [first["baseline_hz"], first["light_hz"], first["post_hz"]],
                "condition": ["baseline", "light", "post"],
            }
        )
    else:
        x_column = str(row.get("x_column", "")).strip()
        y_column = str(row.get("y_column", "")).strip()
        if x_column not in filtered.columns or y_column not in filtered.columns:
            return None
        graph_df = filtered[[x_column, y_column]].copy()
        graph_df.columns = ["x", "y"]
    output_dir = paths["origin_input_dir"] / "graph_inputs"
    output_dir.mkdir(parents=True, exist_ok=True)
    graph_csv = output_dir / f"{graph_name}.csv"
    write_table(graph_df, graph_csv)
    return graph_csv


def _template_for_row(row: pd.Series, paths: dict, config: dict) -> Path | None:
    origin_cfg = _origin_cfg(config)
    if not origin_cfg.get("use_templates", True):
        return None
    templates_dir = Path(origin_cfg.get("templates_dir", paths["origin_templates_dir"]))
    if not templates_dir.is_absolute():
        templates_dir = paths["root_dir"] / templates_dir
    figure_type = str(row.get("figure_type", "")).lower()
    candidates: list[Path] = []
    if "fullrate" in figure_type:
        candidates.extend([paths["origin_template_fullrate"], templates_dir / "FullRate_template.otpu"])
    elif "aligned" in figure_type:
        candidates.extend([templates_dir / "AlignedRate_template.otpu", templates_dir / "PSTH_template.otpu"])
    elif "prelightpost" in figure_type or "prepost" in figure_type:
        candidates.extend([templates_dir / "PreLightPost_template.otpu", templates_dir / "Summary_template.otpu"])
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return None


def _plot_commands_for_row(row: pd.Series, paths: dict, config: dict, graph_csv: Path | None) -> list[str]:
    figure_type = str(row.get("figure_type", ""))
    graph_name = _sanitize_origin_name(row.get("output_graph_name", ""), default="origin_graph")
    output_png = str(row.get("output_png_path", "")).strip()
    template = _template_for_row(row, paths, config)
    workbook_name = _sanitize_origin_name(graph_name, default="origin_data")
    commands = [
        "",
        f"// Graph: {graph_name}",
        f"// Manifest row: file_id={row.get('file_id', '')}; unit_id={row.get('unit_id', '')}; figure_type={figure_type}",
        f'type -a "ORIGIN_OPJU_VERIFY: graph {graph_name}";',
    ]
    if graph_csv is None:
        commands.append("// Skipped: no graph-specific input CSV could be generated for this manifest row.")
        return commands
    commands.extend(
        [
            f"newbook name:={workbook_name} option:=lsname;",
            f'impCSV fname:="{_lt_path(graph_csv)}";',
        ]
    )
    if template is not None:
        commands.append(f'win -t plot "{_lt_path(template)}";')
    else:
        commands.append("win -t plot line;")
    commands.append(f"win -r %H {graph_name};")
    if "prelightpost" in figure_type.lower() or "prepost" in figure_type.lower():
        commands.extend(
            [
                "// Editable summary graph from graph-specific columns: condition_index, firing_rate_hz.",
                f"plotxy iy:=[{workbook_name}]1!(1,2) plot:=203 ogl:=[{graph_name}]1!;",
            ]
        )
    else:
        commands.extend(
            [
                "// Editable trace graph from graph-specific columns: x, y.",
                f"plotxy iy:=[{workbook_name}]1!(1,2) plot:=200 ogl:=[{graph_name}]1!;",
            ]
        )
    if output_png:
        commands.append(f'expGraph type:=png filename:="{output_png.replace(chr(92), "/")}";')
    return commands


def _build_ogs(config: dict, paths: dict, manifest_df: pd.DataFrame, manifest_csv: Path, input_csvs: list[Path]) -> str:
    opju_path = _opju_output_path(config, paths)
    table_cache: dict[str, pd.DataFrame] = {}
    unit_name_map = _unit_original_name_map(paths)
    graph_csvs: dict[int, Path | None] = {
        int(index): _write_graph_input_csv(row, paths, table_cache, unit_name_map)
        for index, row in manifest_df.iterrows()
    }
    lines = [
        "// OriginPro LabTalk script generated by the NeuroExplorer pipeline.",
        "// Run inside OriginPro. Do not run this file with Python.",
        "",
        "[Main]",
        'type -a "ORIGIN_OPJU_VERIFY: entered [Main]";',
        "doc -s;",
        "new;",
        f'string originInputDir$ = "{_lt_path(paths["origin_input_dir"])}";',
        f'string manifestCsv$ = "{_lt_path(manifest_csv)}";',
        f'string opjuOutput$ = "{_lt_path(opju_path)}";',
        "",
        "// Import graph manifest for reference.",
        'type -a "ORIGIN_OPJU_VERIFY: importing manifest";',
        "newbook name:=origin_plot_manifest option:=lsname;",
        'impCSV fname:="$(manifestCsv$)";',
        'type -a "ORIGIN_OPJU_VERIFY: manifest imported";',
        "",
        "// Import Origin-ready input tables.",
    ]
    for csv_path in input_csvs:
        book_name = _sanitize_origin_name(csv_path.stem, default="origin_data")
        lines.extend(
            [
                f'type -a "ORIGIN_OPJU_VERIFY: importing table {book_name}";',
                f"newbook name:={book_name} option:=lsname;",
                f'impCSV fname:="{_lt_path(csv_path)}";',
            ]
        )
    lines.extend(
        [
            "",
            "// Create editable graph pages from imported worksheet columns.",
            "// If a graph template is present under 04_origin_projects/templates, this script starts the graph from that template.",
        ]
    )
    for _, row in manifest_df.iterrows():
        lines.extend(_plot_commands_for_row(row, paths, config, graph_csvs.get(int(row.name))))
    lines.extend(
        [
            "",
            "// Save one Origin project archive.",
            'type -a "ORIGIN_OPJU_VERIFY: saving OPJU $(opjuOutput$)";',
            'save -i "$(opjuOutput$)";',
            'type "Origin project saved to $(opjuOutput$)";',
            'type -a "ORIGIN_OPJU_VERIFY: saved OPJU $(opjuOutput$)";',
            "",
        ]
    )
    return "\n".join(lines)


def generate_origin_script(config: dict, logger: PipelineLogger | None = None) -> dict:
    paths = resolve_project_paths(config)
    for key in ["origin_input_dir", "origin_scripts_dir", "origin_templates_dir", "origin_output_dir"]:
        paths[key].mkdir(parents=True, exist_ok=True)
    origin_cfg = _origin_cfg(config)
    script_format = str(origin_cfg.get("origin_script_format", "ogs")).strip().lower()
    if script_format != "ogs":
        raise ValueError("Only origin.origin_script_format='ogs' is currently supported.")

    manifest_xlsx = paths["origin_input_dir"] / "origin_plot_manifest.xlsx"
    manifest_csv = paths["origin_input_dir"] / "origin_plot_manifest.csv"
    manifest_df = _read_manifest(manifest_xlsx, manifest_csv)
    input_csvs = sorted(
        path
        for path in paths["origin_input_dir"].glob("*.csv")
        if path.name != "origin_plot_manifest.csv"
    )
    script_path = paths["origin_scripts_dir"] / "build_origin_project.ogs"
    readme_path = paths["origin_scripts_dir"] / "README_run_in_origin.md"
    script_path.write_text(_build_ogs(config, paths, manifest_df, manifest_csv, input_csvs), encoding="utf-8")
    readme_path.write_text(SCRIPT_README, encoding="utf-8")
    result = {
        "script_path": str(script_path),
        "readme_path": str(readme_path),
        "manifest_csv_path": str(manifest_csv),
        "opju_output_path": str(_opju_output_path(config, paths)),
        "n_manifest_rows": int(len(manifest_df)),
    }
    if logger is not None:
        logger.log("origin_script", "*", str(manifest_xlsx), str(script_path), "success", f"Wrote OriginPro OGS script. manifest_rows={len(manifest_df)}")
        logger.log("origin_script", "*", "", str(readme_path), "success", "Wrote OriginPro script README.")
    return result


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate OriginPro internal batch plotting scripts.")
    parser.add_argument("--config", required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    config = load_yaml(Path(args.config))
    logger = PipelineLogger(resolve_project_paths(config)["logs_dir"])
    try:
        generate_origin_script(config=config, logger=logger)
        return 0
    finally:
        logger.save()


if __name__ == "__main__":
    raise SystemExit(main())
