from __future__ import annotations

from pathlib import Path

import pandas as pd

from scripts.generate_origin_script import generate_origin_script
from utils.aligned_utils import aligned_window_tag
from utils.logging_utils import PipelineLogger
from utils.path_utils import resolve_project_paths
from utils.table_utils import normalize_include_column, normalize_stim_schedule, read_table, write_table


MANIFEST_COLUMNS = [
    "file_id",
    "unit_id",
    "figure_type",
    "input_csv",
    "x_column",
    "y_column",
    "light_on_s",
    "light_off_s",
    "duration_s",
    "x_min",
    "x_max",
    "output_graph_name",
    "output_png_path",
    "notes",
]


README_TEXT = """# Importing the Origin-ready package

This folder is generated by the Python pipeline so OriginPro can own the final editable graphs.
Python prepares clean tables and a manifest; Origin should import those tables and plot from data columns.

## Package contents

- `../origin_input/fullrate_long.csv`: full-session firing-rate data, when available.
- `../origin_input/aligned_rate_long.csv`: light-aligned firing-rate data, when available.
- `../origin_input/prelightpost_summary.csv`: pre/light/post summary statistics, when available.
- `../origin_input/stim_schedule_master_for_origin.csv`: stimulation timing metadata, when available.
- `../origin_input/unit_quality_table_for_origin.csv`: unit inclusion/QC metadata, when available.
- `../origin_input/origin_plot_manifest.xlsx`: one row per intended graph.

## Recommended OriginPro workflow

1. In OriginPro, create a new project and import the CSV files from `04_origin_projects/origin_input/`.
2. Open `origin_plot_manifest.xlsx` and use each row to identify the input table, X column, Y column, light-band timing, axis range, graph name, and intended export path.
3. Apply your existing Origin graph templates from `04_origin_projects/templates/`.
4. Add light shading using `light_on_s` to `light_off_s`.
5. Export editable Origin graphs or PNG previews to the path listed in `output_png_path`.
6. Save the Origin project under `04_origin_projects/opju_outputs/`.

Do not insert the matplotlib PNGs as the main graph content. The PNGs in `05_exported_figures/` are QC/fallback outputs; the Origin graphs should be generated from imported worksheet columns.
"""


def _plotting_cfg(config: dict) -> dict:
    return config.get("plotting", config.get("neuroexplorer", {}).get("plotting", {}))


def _aligned_cfg(config: dict) -> dict:
    return config.get("aligned_rate", config.get("neuroexplorer", {}).get("aligned_rate", {}))


def _read_many(csv_paths: list[Path], *, source_label: str, logger: PipelineLogger) -> pd.DataFrame:
    frames: list[pd.DataFrame] = []
    for csv_path in csv_paths:
        try:
            frame = read_table(csv_path)
        except Exception as exc:
            logger.log("origin_ready", "*", str(csv_path), "", "warning", f"Failed to read {source_label} table.", exception=exc)
            continue
        if "source_csv" not in frame.columns:
            frame.insert(0, "source_csv", csv_path.name)
        frames.append(frame)
    return pd.concat(frames, ignore_index=True, sort=False) if frames else pd.DataFrame()


def _write_if_not_empty(df: pd.DataFrame, path: Path, logger: PipelineLogger) -> bool:
    if df.empty:
        return False
    write_table(df, path)
    logger.log("origin_ready", "*", "", str(path), "success", f"Wrote Origin input table. rows={len(df)}")
    return True


def _safe_graph_name(*parts: object) -> str:
    text = "_".join(str(part) for part in parts if str(part) != "")
    keep = [ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in text]
    return "_".join("".join(keep).split("_"))[:80] or "origin_graph"


def _range_or_blank(values: pd.Series, reducer: str):
    numeric = pd.to_numeric(values, errors="coerce").dropna()
    if numeric.empty:
        return ""
    return float(numeric.min() if reducer == "min" else numeric.max())


def _text_column(df: pd.DataFrame, column: str) -> pd.Series:
    if column in df.columns:
        return df[column].astype(str)
    return pd.Series([""] * len(df), index=df.index, dtype=str)


def _manifest_row(
    *,
    file_id: str,
    unit_id: str,
    figure_type: str,
    input_csv: str,
    x_column: str,
    y_column: str,
    light_on_s,
    light_off_s,
    duration_s,
    x_min,
    x_max,
    output_dir: Path,
    notes: str = "",
) -> dict:
    graph_name = _safe_graph_name(file_id, unit_id, figure_type)
    return {
        "file_id": file_id,
        "unit_id": unit_id,
        "figure_type": figure_type,
        "input_csv": input_csv,
        "x_column": x_column,
        "y_column": y_column,
        "light_on_s": light_on_s,
        "light_off_s": light_off_s,
        "duration_s": duration_s,
        "x_min": x_min,
        "x_max": x_max,
        "output_graph_name": graph_name,
        "output_png_path": str(output_dir / f"{graph_name}.png"),
        "notes": notes,
    }


def _load_metadata(config: dict, paths: dict, logger: PipelineLogger) -> tuple[pd.DataFrame, pd.DataFrame]:
    try:
        stim_df = normalize_stim_schedule(read_table(paths["stim_schedule_path"]), file_id_column=config["project"]["file_id_column"])
    except Exception as exc:
        logger.log("origin_ready", "*", str(paths["stim_schedule_path"]), "", "warning", "Could not load stim schedule for Origin manifest.", exception=exc)
        stim_df = pd.DataFrame()
    try:
        unit_df = normalize_include_column(read_table(paths["unit_quality_path"]))
    except Exception as exc:
        logger.log("origin_ready", "*", str(paths["unit_quality_path"]), "", "warning", "Could not load unit table for Origin manifest.", exception=exc)
        unit_df = pd.DataFrame()
    return stim_df, unit_df


def _included_units(unit_df: pd.DataFrame, fallback_df: pd.DataFrame, file_id_column: str) -> pd.DataFrame:
    if not unit_df.empty and "include_bool" in unit_df.columns:
        return unit_df[unit_df["include_bool"]].copy()
    if {file_id_column, "unit_id"}.issubset(fallback_df.columns):
        return fallback_df[[file_id_column, "unit_id"]].drop_duplicates().copy()
    return pd.DataFrame(columns=[file_id_column, "unit_id"])


def _first_light_row(stim_df: pd.DataFrame, file_id: str, file_id_column: str) -> pd.Series | None:
    if stim_df.empty or file_id_column not in stim_df.columns:
        return None
    sub = stim_df[stim_df[file_id_column].astype(str) == str(file_id)].copy()
    if sub.empty:
        return None
    light_sub = sub[sub["has_light"].astype(str).str.lower() == "yes"]
    return (light_sub if not light_sub.empty else sub).iloc[0]


def _build_manifest(
    *,
    config: dict,
    paths: dict,
    fullrate_df: pd.DataFrame,
    aligned_df: pd.DataFrame,
    prepost_df: pd.DataFrame,
    stim_df: pd.DataFrame,
    unit_df: pd.DataFrame,
) -> pd.DataFrame:
    file_id_column = config["project"]["file_id_column"]
    output_dir = paths["origin_output_dir"]
    included = _included_units(unit_df, pd.concat([fullrate_df, aligned_df, prepost_df], ignore_index=True, sort=False), file_id_column)
    rows: list[dict] = []
    plotting_cfg = _plotting_cfg(config)
    aligned_cfg = _aligned_cfg(config)
    aligned_tag = aligned_window_tag(aligned_cfg)

    for unit_row in included.itertuples(index=False):
        file_id = str(getattr(unit_row, file_id_column))
        unit_id = str(getattr(unit_row, "unit_id"))
        unit_candidates = {unit_id}
        if hasattr(unit_row, "original_name"):
            unit_candidates.add(str(getattr(unit_row, "original_name")))
        stim_row = _first_light_row(stim_df, file_id, file_id_column)
        light_on = "" if stim_row is None or pd.isna(stim_row.get("light_on_s", pd.NA)) else float(stim_row["light_on_s"])
        duration = "" if stim_row is None or pd.isna(stim_row.get("duration_s", pd.NA)) else float(stim_row["duration_s"])
        light_off = "" if stim_row is None or pd.isna(stim_row.get("light_off_s", pd.NA)) else float(stim_row["light_off_s"])
        full_sub = fullrate_df[(_text_column(fullrate_df, file_id_column) == file_id) & (_text_column(fullrate_df, "unit_id").isin(unit_candidates))]
        if not full_sub.empty:
            rows.append(
                _manifest_row(
                    file_id=file_id,
                    unit_id=unit_id,
                    figure_type="fullrate",
                    input_csv="fullrate_long.csv",
                    x_column="time_bin_center_s",
                    y_column="firing_rate_hz",
                    light_on_s=light_on,
                    light_off_s=light_off,
                    duration_s=duration,
                    x_min=_range_or_blank(full_sub["time_bin_center_s"], "min") if "time_bin_center_s" in full_sub.columns else "",
                    x_max=_range_or_blank(full_sub["time_bin_center_s"], "max") if "time_bin_center_s" in full_sub.columns else "",
                    output_dir=output_dir,
                    notes="Full-session absolute-time graph; shade light_on_s to light_off_s.",
                )
            )
        aligned_sub = aligned_df[(_text_column(aligned_df, file_id_column) == file_id) & (_text_column(aligned_df, "unit_id").isin(unit_candidates))]
        if not aligned_sub.empty:
            aligned_duration = _range_or_blank(aligned_sub["duration_s"], "max") if "duration_s" in aligned_sub.columns else duration
            x_min = _range_or_blank(aligned_sub["aligned_time_s"], "min") if "aligned_time_s" in aligned_sub.columns else float(aligned_cfg.get("x_min_s", -60))
            x_max = _range_or_blank(aligned_sub["aligned_time_s"], "max") if "aligned_time_s" in aligned_sub.columns else float(aligned_cfg.get("x_max_s", 75))
            rows.append(
                _manifest_row(
                    file_id=file_id,
                    unit_id=unit_id,
                    figure_type=f"aligned_rate_{aligned_tag}",
                    input_csv="aligned_rate_long.csv",
                    x_column="aligned_time_s",
                    y_column="firing_rate_hz",
                    light_on_s=float(plotting_cfg.get("aligned_light_band_start_s", 0.0)),
                    light_off_s=aligned_duration,
                    duration_s=aligned_duration,
                    x_min=x_min,
                    x_max=x_max,
                    output_dir=output_dir,
                    notes="Light-on aligned graph; shade 0 to duration_s.",
                )
            )
        prepost_sub = prepost_df[(_text_column(prepost_df, file_id_column) == file_id) & (_text_column(prepost_df, "unit_id").isin(unit_candidates))]
        if not prepost_sub.empty:
            rows.append(
                _manifest_row(
                    file_id=file_id,
                    unit_id=unit_id,
                    figure_type="prelightpost_summary",
                    input_csv="prelightpost_summary.csv",
                    x_column="baseline_hz;light_hz;post_hz",
                    y_column="firing_rate_hz",
                    light_on_s=0.0,
                    light_off_s=duration,
                    duration_s=duration,
                    x_min="",
                    x_max="",
                    output_dir=output_dir,
                    notes="Use baseline_hz, light_hz, and post_hz as editable bar values.",
                )
            )

    return pd.DataFrame(rows, columns=MANIFEST_COLUMNS)


def export_origin_ready_package(config: dict, logger: PipelineLogger) -> dict:
    paths = resolve_project_paths(config)
    for key in ["origin_input_dir", "origin_scripts_dir", "origin_templates_dir", "origin_output_dir"]:
        paths[key].mkdir(parents=True, exist_ok=True)

    input_dir = paths["origin_input_dir"]
    fullrate_df = _read_many(sorted(paths["nex_fullrate_dir"].glob("*.csv")), source_label="fullrate", logger=logger)
    aligned_paths = [path for path in sorted(paths["nex_aligned_rate_dir"].glob("*.csv")) if "PreLightPostSummary" not in path.name]
    aligned_df = _read_many(aligned_paths, source_label="aligned_rate", logger=logger)
    prepost_df = _read_many(sorted(paths["nex_aligned_rate_dir"].glob("*PreLightPostSummary*.csv")), source_label="prelightpost_summary", logger=logger)
    stim_df, unit_df = _load_metadata(config, paths, logger)

    written: list[str] = []
    for df, filename in [
        (fullrate_df, "fullrate_long.csv"),
        (aligned_df, "aligned_rate_long.csv"),
        (prepost_df, "prelightpost_summary.csv"),
        (stim_df, "stim_schedule_master_for_origin.csv"),
        (unit_df, "unit_quality_table_for_origin.csv"),
    ]:
        out_path = input_dir / filename
        if _write_if_not_empty(df, out_path, logger):
            written.append(str(out_path))

    manifest_df = _build_manifest(
        config=config,
        paths=paths,
        fullrate_df=fullrate_df,
        aligned_df=aligned_df,
        prepost_df=prepost_df,
        stim_df=stim_df,
        unit_df=unit_df,
    )
    manifest_path = input_dir / "origin_plot_manifest.xlsx"
    write_table(manifest_df, manifest_path)
    written.append(str(manifest_path))
    readme_path = paths["origin_scripts_dir"] / "README_import_to_origin.md"
    readme_path.write_text(README_TEXT, encoding="utf-8")
    written.append(str(readme_path))
    script_result = None
    if config.get("origin", {}).get("generate_origin_script", True):
        script_result = generate_origin_script(config=config, logger=logger)
        written.extend([script_result["script_path"], script_result["readme_path"], script_result["manifest_csv_path"]])
    logger.log("origin_ready", "*", "", str(manifest_path), "success", f"Wrote Origin plot manifest. rows={len(manifest_df)}")
    logger.log("origin_ready", "*", "", str(readme_path), "success", "Wrote Origin import README.")
    return {
        "origin_input_dir": str(input_dir),
        "manifest_path": str(manifest_path),
        "readme_path": str(readme_path),
        "origin_script": script_result,
        "written_files": written,
        "manifest_rows": len(manifest_df),
    }
